# Generated by Django 4.2.27 on 2026-04-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Can',
            fields=[
                ('ma_can', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ma can')),
                ('ten_can', models.CharField(max_length=200, verbose_name='Ten can')),
                ('vi_tri', models.CharField(max_length=200, verbose_name='Vi tri')),
                ('hang', models.CharField(max_length=100, verbose_name='Hang san xuat')),
                ('ngay_lap_dat', models.DateField(verbose_name='Ngay lap dat')),
                ('khoi_luong_toi_da', models.FloatField(verbose_name='Khoi luong toi da (kg)')),
                ('api', models.CharField(max_length=500, verbose_name='API endpoint')),
                ('hoat_dong', models.BooleanField(default=True, verbose_name='Hoat dong')),
            ],
            options={
                'verbose_name': 'Can',
                'verbose_name_plural': 'Danh sach can',
                'ordering': ['ma_can'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_camera', models.CharField(max_length=200, verbose_name='Ten camera')),
                ('api', models.CharField(max_length=500, verbose_name='API/Endpoint WebRTC')),
                ('hoat_dong', models.BooleanField(default=True, verbose_name='Hoat dong')),
                ('can', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='can.can', verbose_name='Can')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Danh sach camera',
            },
        ),
        migrations.CreateModel(
            name='BanGhiCan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khoi_luong', models.FloatField(verbose_name='Khoi luong (kg)')),
                ('anh', models.ImageField(blank=True, null=True, upload_to='ban_ghi/', verbose_name='Anh')),
                ('thoi_gian', models.DateTimeField(verbose_name='Thoi gian')),
                ('du_lieu_goc', models.TextField(default='{}', verbose_name='Du lieu goc')),
                ('can', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_ghi', to='can.can', verbose_name='Can')),
            ],
            options={
                'verbose_name': 'Ban ghi can',
                'verbose_name_plural': 'Ban ghi can',
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
